#pragma once

#include <SDL3/SDL.h>

enum CUSTOM_LOG_CATEGORY{
    CUSTOM_LOG_CATEGORY_EXPLORER = SDL_LOG_CATEGORY_CUSTOM,
    CUSTOM_LOG_CATEGORY_TEXT,
    CUSTOM_LOG_CATEGORY_EDITOR,
    CUSTOM_LOG_CATEGORY_INPUT,
    CUSTOM_LOG_CATEGORY_LAST,
};
